sudo: false    # Use container-based infrastructure
language: python
python:
  - 2.6    
  - 2.7
  - 3.3
  - 3.4
  - 3.5
# setup miniconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
# install packages
install:
    - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose pip coverage
    - source activate testenv  
    - pip install nose-cov
    - pip install python-coveralls
    - python setup.py install
script:
    - mkdir tmp  # so that we don't pick up source directory
    - cd tmp
    - nosetests -v --with-cov --cov nmrglue --exe nmrglue
after_success:
    - coveralls
